### ISSUE TITLE
Generate ACF json files

### ISSUE THREAD

**Issue by marcelo2605** [RadishLab/pro011#7]

**Comment by alesub** [comment]
Issue deployed.

**Comment by marcelo2605** [comment]
Thanks @alesub. In the current website, some ACF groups are duplicated. In this issue, I removed the duplicated groups. But in the [staging website](https://dev-pro011.pantheonsite.io/wp/wp-admin/edit.php?post_type=acf-field-group&orderby=title&order=asc), its appeared again. I try to sync, but nothing happens.
